services:
  db:
    build: ./infra/db/
    ports:
      - 5432:5432
    container_name: db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - internal

  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - backend_volume:/app/src/saved
    networks:
      - internal
      - external

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - external
    ports:
      - 8080:80

  prometheus:
    build: ./infra/monitoring/prometheus
    container_name: prometheus
    networks:
      - internal

  grafana:
    build: ./infra/monitoring/grafana
    container_name: grafana
    networks:
      - internal
    ports:
      - 3000:3000

volumes:
  db_volume:
  backend_volume:

networks:
  external:
    driver: bridge

  internal:
    driver: bridge
